Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,20 +1,22 @@
-name: Run Bash Script
+stages:
+  - check_code
 
-on:
-  push:
-    branches:
-      - stage  # Adjust the branch name as needed
+check_code:
+  stage: check_code
+  script:
+    - git fetch origin $CI_MERGE_REQUEST_TARGET_BRANCH_DEV:$CI_MERGE_REQUEST_TARGET_BRANCH_DEV
+    - git checkout $CI_MERGE_REQUEST_TARGET_BRANCH_DEV
+    - git diff --name-only origin/$CI_MERGE_REQUEST_TARGET_BRANCH_DEV...$CI_COMMIT_SHA | while read -r FILE; do
+        if [ -f "$FILE" ]; then
+          git diff origin/$CI_MERGE_REQUEST_TARGET_BRANCH_DEV...$CI_COMMIT_SHA "$FILE" | grep -q "diff --git";
+          if [ $? -eq 0 ]; then
+            echo "File $FILE contains new changes";
+            exit 1; # Fail the pipeline if there are new changes
+          fi
+        fi
+      done
+  only:
+    - merge_requests
+  except:
+    - branches
 
-jobs:
-  run-bash-script:
-    runs-on: ubuntu-latest
-
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v2
-
-      - name: Run Bash script
-        run: bash .github/script.sh
-      - name: Fail the workflow if differences are found
-        if: ${{ failure() }}
-        run: exit 1        
